version: '3.8'

services:
  wordpress:
    image: wordpress:php8.2-fpm-alpine
    container_name: wordpress_app
    restart: always
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wp_network

  db:
    image: mariadb:latest
    container_name: wordpress_db
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  nginx:
    image: nginx:alpine
    container_name: wordpress_nginx
    restart: always
    depends_on:
      - wordpress
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./wordpress:/var/www/html
    networks:
      - wp_network
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`yourdomain.com`)" # Change to your actual domain
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=myresolver"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"

networks:
  wp_network:
  traefik:
    external: true

volumes:
  db_data:
